<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-PaymentsApi-f618502b-ea33-46a1-a8ab-b24178d55704</UserSecretsId>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<!-- <ContainerFamily>noble-chiseled</ContainerFamily> -->
		<!--<ContainerUser>app</ContainerUser>-->
	</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
        <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
        <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="4.14.2" />
        <PackageReference Include="Azure.Storage.Queues" Version="12.27.1" />
        <PackageReference Include="Scrutor" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Models\Models.csproj" />
        <ProjectReference Include="..\MiniBank.ServiceDefaults\MiniBank.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
